# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-25 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.TextField(choices=[('New', 'New Leave'), ('Approved', 'Approved Leave'), ('Declined', 'Declined Leave')]),
        ),
    ]
