# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-26 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_auto_20170225_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='daysOfLeave',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='leave',
            name='startDate',
            field=models.DateTimeField(),
        ),
    ]
