# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-27 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_auto_20170226_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='remainingLeaveDays',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leave',
            name='daysOfLeave',
            field=models.IntegerField(default=0),
        ),
    ]
