# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-27 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_auto_20170227_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.TextField(default=''),
        ),
    ]
