# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-27 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_leave_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='username',
            field=models.TextField(),
        ),
    ]
