# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-27 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0010_auto_20170227_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='startDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leave',
            name='endDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leave',
            name='startDate',
            field=models.DateField(),
        ),
    ]
